default_platform(:ios)

platform :ios do
  desc "Build e envia uma build para o TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"], # .p8 já decodificado em disco pelo workflow
      in_house: false
    )

    build_app(
      project: "Center Rent V2.xcodeproj",
      scheme: "Center Rent V2",
      export_method: "app-store",
      output_directory: "build",
      export_options: {
        provisioningProfiles: {
          ENV["APP_IDENTIFIER"] => ENV["PROVISIONING_PROFILE_NAME"]
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
